#pragma once

#include <array>
#include <string_view>

namespace manelemax
{

using namespace std::string_view_literals;

constexpr std::array g_keywords {
    "nicolae guta"sv,
    "florin salam"sv,
    "tzanca uraganu"sv,
    "tzanca uraganul"sv,
    "romeo fantastik"sv,
    "romeo fantastick"sv,
    "manele"sv,
    "narcis"sv,
    "narcisa"sv,
    "florin crisan"sv,
    "costi ionita"sv,
    "cristian rizescu"sv,
    "costel ciofu"sv,
    "modjo"sv,
    "nicoleta guta"sv,
    "babi minune"sv,
    "susanu"sv,
    "florin minune"sv,
    "zaku"sv,
    "mihaela minune"sv,
    "mr juve"sv,
    "blondu de la timisoara"sv,
    "liviu guta"sv,
    "play aj"sv,
    "dani mocanu"sv,
    "costel pustiu"sv,
    "sorinel pustiu"sv,
    "liviu mititelu"sv,
    "liviu mititelul"sv,
    "adi de la valcea"sv,
    "nek"sv,
    "marius de la focsani"sv,
    "adrian minune"sv,
    "adrian copilul minune"sv,
    "adrian copilu minune"sv,
    "sandu ciorba"sv,
    "sorin copilu de aur"sv,
    "sorin copilul de aur"sv,
    "dan ciotoi"sv,
    "bogdan dlp"sv,
    "bogdan de la ploiesti"sv,
    "dj sebi"sv,
    "nyno"sv,
    "florin mitroi"sv,
    "sorina ceugea"sv,
    "don genove"sv,
    "cocos de la calarasi"sv,
    "ionut cercel"sv,
    "petrica cercel"sv,
    "printesa de aur"sv,
    "edy talent"sv,
    "jean de la craiova"sv,
    "ionut de la constanta"sv,
    "geany morandi"sv,
    "costel biju"sv,
    "antonio minune"sv,
    "babi minune"sv,
    "denisa"sv,
    "brazilianu"sv,
    "brazilianul"sv,
    "geo"sv,
    "liviu pustiu"sv,
    "fernando de la caransebes"sv,
    "mogjo"sv,
    "bogdan artistu"sv,
    "bogdan artistul"sv,
    "cristi dules"sv,
    "alex de la orastie"sv,
    "alessio"sv,
    "florinel"sv,
    "stelica de la craiova"sv,
    "dani printul banatului"sv,
    "dani printu banatului"sv,
    "costi de la timisoara"sv,
    "valentino"sv,
    "mitzu din salaj"sv,
    "minodora"sv,
    "a-tentat"sv,
    "leonard"sv,
    "eduard de la roma"sv,
    "raluca dragoi"sv,
    "mihaita piticu"sv,
    "nino"sv,
    "adriano"sv,
    "lucian printu"sv,
    "lucian printul"sv,
    "kristiyana"sv,
    "marius babanu"sv,
    "asu"sv,
    "nicu guta"sv,
    "vali vijelie"sv,
    "boby"sv,
    "stana izbasa"sv,
    "lepa brena"sv,
    "gerard inima de leu"sv,
    "lepa brena"sv,
    "fero"sv,
    "florin universalu"sv,
    "florin universalul"sv,
    "leo de la kuweit"sv,
    "iuli neamtu"sv,
    "iuly neamtu"sv,
    "jador"sv,
    "ghita adriano"sv,
    "babasha"sv,
    "brandy"sv,
    "amma music sound"sv,
    "big man romania"sv,
    "vocea bagabontilor"sv,
    "kompact play music"sv,
    "x pert production official"sv,
    "theo rose"sv,
    "viper production"sv,
    "autenticmusicromania"sv,
    "danezu music"sv,
};

}  // namespace manelemax
